esphome:
  name: sonoff1
  includes:
  - nockanda_espnow.h
  
esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "b1e54e1475c86916fe051bf35a8853b2"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Sonoff Basic Button"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Sonoff Basic Relay"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes

custom_component:
- lambda: |-
       NOCKANDA_ESPNOW.begin();
       NOCKANDA_ESPNOW.turn_on([]() {
          //
       });
       NOCKANDA_ESPNOW.turn_off([]() {
          id(relay).toggle();
       });
       return {};

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff1 Fallback Hotspot"
    password: "vVeNylpba2m5"

captive_portal:
    